# DO NOT EDIT THIS FILE DIRECTLY
# This is a file generated from a literate programing source file located at
# https://github.com/caiomoritz/dot-ruby/-/blob/master/.irbrc.org
# You can always recreate it from within init.org using C-c C-v t (org-babel-tangle)

IRB.conf[:USE_MULTILINE] = false if ENV['INSIDE_EMACS']
IRB.conf[:USE_READLINE] = false if ENV['INSIDE_EMACS']
